micronaut:
  server:
    port: 8081
  application:
    name: keyManagerGrpc
grpc:
  channels:
    all:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/key-manager-grpc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: zupedu
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
client:
  contas:
    itau: ${ITAU_CLIENT_ADDRESS:`http://localhost:9091/api/v1/clientes`}
    bcb: ${BCB_CLIENT_ADDRESS:`http://localhost:8082/api/v1/pix/keys`}

